PUT http://localhost:3001/api/blogs/64357ea08bffafeed01145e0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJjdHluZXIiLCJpZCI6IjY0MzRjOTliNmQ0MzU5ZGI2NDcwZjRlOCIsImlhdCI6MTY4MTIyNTQ1OCwiZXhwIjoxNjgxMjI5MDU4fQ.TlPhjJZUUGu5Owa0uHdYO8Z5X-rPZDW-7EOIjJnDDHY

{
    "title": "newBlogTitle",
    "author": "newBlogAuthor",
    "url": "newBlogUrl",
    "likes": 2
}